# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Builder-Magic
version:      1.3
version_from: lib/CGI/Builder/Magic.pm
installdirs:  site
requires:
    CGI::Builder:                  1.3
    Class::groups:                 2.1
    Class::props:                  2.1
    Class::Util:                   2.1
    Object::props:                 2.1
    Template::Magic:               1.36

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
