# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Builder-Magic
version:      1.28
version_from: lib/CGI/Builder/Magic.pm
installdirs:  site
requires:
    CGI::Builder:                  1.2
    Class::groups:                 1.62
    Class::props:                  1.62
    Object::props:                 1.62
    Template::Magic:               1.33

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
