# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Builder-Magic
version:      1.24
version_from: 
installdirs:  site
requires:
    CGI::Builder:                  1.2
    Template::Magic:               1.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
